version: '3.8'

services:
  mcp-server-milvus:
    build: .
    container_name: mcp-server-milvus
    ports:
      - "${MCP_PORT:-8000}:8000"
    environment:
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
      - MILVUS_USER=${MILVUS_USER}
      - MILVUS_PASSWORD=${MILVUS_PASSWORD}
      - MILVUS_DB_NAME=${MILVUS_DB_NAME:-default}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3